### ISSUE TITLE
AppCode 3.1 fails to launch with GLSL plugin enabled

### ISSUE THREAD

**Issue by pocketpixels** [Darkyenus/glsl4idea#84] opened 2015-07-01 00:08 UTC
Using AppCode 3.1 (139.1402) and GLSL plugin 1.8 I receive the following error after enabling the GSLS plugin and re-starting AppCode: 

Plugin 'GLSL' failed to initialize and will be disabled.  Please restart AppCode.
```
java.lang.NoSuchMethodError: com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance()Lcom/intellij/ide/fileTemplates/FileTemplateManager;
    at glslplugin.components.GLSLTemplatesLoader.initComponent(GLSLTemplatesLoader.java:39)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:567)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:358)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by AbigailBuccaneer** [comment] 2015-07-01 00:22
Looks like a duplicate of #74, which has been fixed since the latest release.

@Darkyenus is it time to roll out a new release?

**Closed by AbigailBuccaneer** 2015-07-01 00:22 UTC

**Comment by Darkyenus** [comment] 2015-07-01 09:30
Indeed it is!

**Comment by pocketpixels** [comment] 2015-07-02 06:28
Version 1.9 works great in AppCode. Thanks guys!
