### ISSUE TITLE
Function calls are parsed as constructors

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Darkyenus/glsl4idea#86] opened 2015-07-01 10:22 UTC
Function calls are seemingly all getting parsed as constructors, which means they're all doing type conversions to struct types which don't exist.

```GLSL
int f();

void main() {
    int x = f(); // error: can't assign 'f' to 'int'
    vec3 x = normalize(vec3(1.f)); // error: can't assign 'normalize' to 'vec3'
}
```

**Comment by AbigailBuccaneer** [comment] 2015-07-01 10:23
@Darkyenus this is fairly serious :(

**Comment by AbigailBuccaneer** [comment] 2015-07-01 10:27
Okay, it looks like the cause is that `parseFunctionIdentifier` tries to parse a type specifier, and if it can then it assumes it's a constructor. But a single identifier is a valid type specifier (it's a reference to an existing struct type).

I think given this there's probably no sensible way to separate constructors and functions at the parsing level - that distinction should come higher up, when a function/constructor call would resolve to either a function declaration or struct name (and the return type would be based on that).

**Comment by Darkyenus** [comment] 2015-07-01 10:27
Noticed during prerelease testing as well, fixed in 56803589aab6cfca2617f3897ac26e08e97cf03b. It is not ideal, since structures can have constructors as well.

**Comment by Darkyenus** [comment] 2015-07-01 10:30
Yeah, I'll look into that later, for now it should work well enough. The problem is, that it needs a reliable way to tell whether the name of function call corresponds to defined structure. Is that possible? This seems vaguely related to your work around rename refactoring.

**Comment by AbigailBuccaneer** [comment] 2015-07-01 10:31
I'm going to be doing even more work on references - it should be possible to reliably resolve the name to either a struct type or a function name.

**Comment by Darkyenus** [comment] 2015-07-01 10:36
When I tested it now on master, the struct name refactoring didn't work yet, but valid code involving structure constructor was not highlighted as error. So I won't postpone the release because of it and the constructor related code can be refactored back into function calls in next release.

**Closed** 2015-07-01 10:36 UTC
Labels: bug
