### ISSUE TITLE
Problem with definitions with arguments

### ISSUE THREAD

**Issue by lamerman** [Darkyenus/glsl4idea#124] opened 2017-07-05 10:38 UTC
I have definition with multiple arguments. Every usage of this definition is marked as error in IDEA, though the compiler compiles it without errors.

```
#define SET_BIT(bitIndex, resultArray, isLess) \
    if (isLess) { resultArray[bitIndex/32U] |= 1U << (bitIndex % 32U); } \
    bitIndex++
```

This is an example of such definition

**Comment by Darkyenus** [comment] 2017-07-05 11:25
Function #defines are sadly not yet supported. You can disable error checking to get at least some highlighting out of the plugin by clicking the face in the bottom right corner.

**Comment by Darkyenus** [comment] 2022-04-05 17:08
Duplicate of #144. (Yes, it is the other way around, but that one has better name.)

**Closed by Darkyenus** 2022-04-05 17:08 UTC
